### ISSUE TITLE
[SP5] Conclude React CSS Style guide

### ISSUE THREAD

**Issue by sandysaille** [prontotools/simplesat#17]
As Pronto Tools, I want to research on React CSS practice that suits our styles so that our code will be maintainable.

**Exit Criteria**
- [x] Have list of React CSS practices and talked to the team
- [x] Complete React CSS style guide

**Comment by oy-np** [comment]
* style ใน component เลยมั้ย? หรือ div เอาตอนเรียกใช้ component
  * ตัว component ไม่ fix width, center, padding  ได้นิดหน่อย
  * fix height เป็น px ได้
* constructor ไม่ต้องเขียนก็ได้
* fuction เขียนเอง ไม่ต้องมี _
* function ที่ไม่ใช้ properties ที่เกี่ยวข้องกับ class นั้นๆให้ไว้นอก * style ใน component เลยมั้ย? หรือ div เอาตอนเรียกใช้ component
  * ตัว component ไม่ fix width, center, padding  ได้นิดหน่อย
  * fix height เป็น px ได้
* constructor ไม่ต้องเขียนก็ได้
* fuction เขียนเอง ไม่ต้องมี _
* function ที่ไม่ใช้ properties ที่เกี่ยวข้องกับ class นั้นๆให้ไว้นอก class

**Comment by lukyth** [comment]
- Every presentation component should export AcceptStyleAndClassName(ComponentName) as `ComponentNameStyle`
- Use ComponentName or ComponentNameStyle as you see fits
- Use `static propTypes = {}` in the class instead of `className.propTypes` outside of class
- Presentation component don’t have to work 100% itself
- Write Media Query in its own class
- Use compose when base class is used by some component
- Use placeholder when no variable is needed
- Use mixin when variable is needed
- Not compress image on development
- Use camelCase for class name

**Comment by lukyth** [comment]
- Use CSS Modules's `composes` for  same-for-a-reason
- Use SASS's `mixin` for same-just-because
- If you think you should use SASS's `placeholder`, reconsider and use `composes`
